### ISSUE TITLE
Handle multiple windows

### ISSUE THREAD

**Issue by aphilas** [uBlockOrigin/uBOL-issues#14]
I have two monitors. Clicking the uBOL extension button on Window 2 brings up the setting for the active tab of the window on the primary monitor rather than the window I'm on (the secondary monitor).

Example:

```
window 1, monitor 1   window 2, monitor 2

+-------------------+ +--------------------+
| github.com        | | wikifeet.com       |
|                   | |       +----------+ |
|                   | |       |basic     | |
|                   | |       |   x      | |
|                   | |       |xxxxxxxxxx| |
|                   | |       |   x      | |
|                   | |       |github.com| |
|                   | |       +----------+ |
|                   | |                    |
|                   | |                    |
+-------------------+ +--------------------+
```

Linux 5.4.0-132-generic | ~18.04.1-Ubuntu
Chrome Version 107.0.5304.110 (Official Build) (64-bit)
uBlock Origin Lite 0.1.22.11165

**Comment by gorhill** [comment]
I don't have two monitors so I can't test if the change fixes this. You will have to report back if it's fixed in the next release.

**Comment by aphilas** [comment]
I have disconnected the second monitor and the issue still persists (with
two windows).

Am I missing something?

Does it work with multiple windows on your computer?

**Comment by aphilas** [comment]
I have seen the referenced commit. Appears to fix the issue. 

I presume `await chrome.tabs.query({ active: true, currentWindow: true })` would also work, no?

I have also installed the dev version and will await the release with the fix and report back here.

**Comment by gorhill** [comment]
> I presume `await browser.tabs.query({ active: true, currentWindow: true })` would also work, no?

Thanks for pointign this out, I will this instead.
